<a href="https://colab.research.google.com/github/manas-techie/ML-Basic/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY - Numerical Python

### Advantages of Numpy
       1. Allows Several Mathematical Operations
       2. Faster Operations

In [1]:
import numpy as np

List vs Numpy - Time Taken

In [2]:
from time import process_time

Check Numpy version

In [41]:
print(np.__version__)

2.0.2


Time taken by a list

In [3]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0007764999999999578


Time Taken by Numpy

In [4]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  # Add 5 to the all elements of the numpy_array

end_time = process_time()

print(end_time - start_time)

0.0010576620000000148


Numpy Arrays

In [5]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [6]:
#Numpy Array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [7]:
# creating a 1 dimensional array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape #check the dimension of the array

(4,)

In [9]:
#create a 2 dimensional array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [10]:
b.shape

(2, 4)

In [44]:
#create 3d array
arr3d = np.array([[[1, 2], [3, 4]], [[4, 5],[6, 7]]])
print(arr3d)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [45]:
print(arr3d.shape)

(2, 2, 2)


In [46]:
#Array with a specific datatype
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float) #dtype use to mention the datatype
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Intial Paceholder in numpy array or built-in Array Creation function

In [12]:
#create a numpy arrays of zeros
x = np.zeros((4,5)) #((row,col))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#create an array of particular value
z = np.full((5,4),10) #((row,col),value)
print(z)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [47]:
#create a array with Range of values
arange = np.arange(10,30,3) # start,end,step
print(arange)

[10 13 16 19 22 25 28]


In [15]:
#create an indentity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
#create a numpy array with random values
b = np.random.random((3,4)) # the values will be 0 - 1
print(b)

[[0.53228962 0.4195149  0.00571996 0.45941701]
 [0.62199225 0.84003768 0.06880346 0.20757049]
 [0.46456588 0.18303194 0.82785623 0.47944967]]


In [17]:
#random values arrays the values will be integer with in a specific range
c = np.random.randint(10,100,(3,5)) #((min,max),(row,col))
print(c)

[[53 64 89 34 42]
 [63 94 84 89 85]
 [40 45 29 66 82]]


In [18]:
#Array of evenly spaced value --- Specifying the number of values required
d = np.linspace(10,30,6) #((min,max),no_of_element)
print(d)

[10. 14. 18. 22. 26. 30.]


In [19]:
#array of evenly spaced values -- specifying the step
e = np.arange(10,30,5) #((min,max,step))
print(e)

[10 15 20 25]


In [20]:
#convert a list into numpy array
list2 = [10,20,30,40,50]
print(list2)
print(type(list2))
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10, 20, 30, 40, 50]
<class 'list'>
[10 20 30 40 50]


numpy.ndarray

Analysing a Numpy Array

In [21]:
c = np.random.randint(10,100,(5,5))
print(c)

[[38 18 71 34 63]
 [98 84 83 28 86]
 [49 20 92 99 29]
 [14 18 54 49 15]
 [79 18 70 35 71]]


In [22]:
#Array dimension
print(c.shape)

(5, 5)


In [23]:
#Number of dimension
print(c.ndim)

2


In [24]:
#number of element present in array
print(c.size)

25


In [25]:
#the datatype of the array element
print(c.dtype)

int64


Mathematical Operations On np Array

In [26]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2)  #concatenate or jion two array

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [27]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[7 7 1]
 [0 1 9]
 [1 0 0]]
[[12 18 17]
 [14 12 16]
 [18 17 13]]


In [28]:
print(a+b) #Its the operation of element wise addition

[[19 25 18]
 [14 13 25]
 [19 17 13]]


In [29]:
print(a-b) #Its the operation of element wise subtraction

[[ -5 -11 -16]
 [-14 -11  -7]
 [-17 -17 -13]]


In [30]:
print(a*b) #Its the operation of element wise multiplication

[[ 84 126  17]
 [  0  12 144]
 [ 18   0   0]]


In [31]:
print(a/b) #Its the operation of element wise division

[[0.58333333 0.38888889 0.05882353]
 [0.         0.08333333 0.5625    ]
 [0.05555556 0.         0.        ]]


In [32]:
print(np.add(a,b))

[[19 25 18]
 [14 13 25]
 [19 17 13]]


In [33]:
print(np.subtract(a,b))

[[ -5 -11 -16]
 [-14 -11  -7]
 [-17 -17 -13]]


In [34]:
print(np.multiply(a,b))

[[ 84 126  17]
 [  0  12 144]
 [ 18   0   0]]


In [35]:
print(np.divide(a,b))

[[0.58333333 0.38888889 0.05882353]
 [0.         0.08333333 0.5625    ]
 [0.05555556 0.         0.        ]]


Array Manipulation

In [36]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 3 3]
 [8 7 5]]
(2, 3)


In [37]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[7 8]
 [3 7]
 [3 5]]
(3, 2)


In [38]:
trans2 = array.T #Another method of transpose
print(trans2)
print(trans2.shape)

[[7 8]
 [3 7]
 [3 5]]
(3, 2)


In [39]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[7 0 6]
 [5 9 7]]
(2, 3)


In [40]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[7 0]
 [6 5]
 [9 7]]
(3, 2)
