<a href="https://colab.research.google.com/github/manas-techie/ML-Basic/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY - Numerical Python

### Advantages of Numpy
       1. Allows Several Mathematical Operations
       2. Faster Operations

ARRAY CREATION:
- np.array([1,2,3])         → From list
- np.zeros(5)               → Array of zeros
- np.ones((3,4))            → Matrix of ones
- np.arange(0,10,2)         → Range with step
- np.linspace(0,1,5)        → Evenly spaced
- np.random.random((2,3))   → Random values

ARRAY PROPERTIES:
- arr.shape    → Dimensions
- arr.size     → Total elements
- arr.dtype    → Data type
- arr.ndim     → Number of dimensions

RESHAPING:
- arr.reshape(3,4)  → Change shape
- arr.flatten()     → To 1D
- arr.T             → Transpose

INDEXING:
- arr[0]        → First element
- arr[1:4]      → Slice
- arr[arr > 5]  → Boolean indexing
- arr2d[1,2]    → 2D indexing

OPERATIONS:
- arr + 10      → Add scalar
- arr1 + arr2   → Element-wise add
- np.sum(arr)   → Sum all
- np.mean(arr)  → Average
- np.max(arr)   → Maximum
- np.sqrt(arr)  → Square root

MANIPULATION:
- np.concatenate([a,b])  → Join arrays
- np.vstack([a,b])       → Vertical stack
- np.hstack([a,b])       → Horizontal stack
- np.sort(arr)           → Sort array
- np.unique(arr)         → Unique values

REMEMBER:
✓ NumPy is 10-100x faster than Python lists
✓ All elements must be same type
✓ Operations are element-wise by default
✓ Use axis=0 for columns, axis=1 for rows
✓ Broadcasting allows different shapes
"""

In [371]:
import numpy as np

List vs Numpy - Time Taken

In [372]:
from time import process_time

Check Numpy version

In [373]:
print(np.__version__)

2.0.2


Time taken by a list

In [374]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0005504409999979032


Time Taken by Numpy

In [375]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5  # Add 5 to the all elements of the numpy_array

end_time = process_time()

print(end_time - start_time)

0.00015126100000273368


Numpy Arrays

In [376]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [377]:
#Numpy Array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [378]:
# creating a 1 dimensional array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [379]:
a.shape #check the dimension of the array

(4,)

In [380]:
#create a 2 dimensional array
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [381]:
b.shape

(2, 4)

In [382]:
#create 3d array
arr3d = np.array([[[1, 2], [3, 4]], [[4, 5],[6, 7]]])
print(arr3d)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [383]:
print(arr3d.shape)

(2, 2, 2)


In [384]:
#Array with a specific datatype
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float) #dtype use to mention the datatype
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Intial Paceholder in numpy array or built-in Array Creation function

In [385]:
#create a numpy arrays of zeros
x = np.zeros((4,5)) #((row,col))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [386]:
#create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [387]:
#create an array of particular value
z = np.full((5,4),10) #((row,col),value)
print(z)

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


In [388]:
#create an indentity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [389]:
#create a numpy array with random values
b = np.random.random((3,4)) # the values will be 0 - 1
print(b)

[[0.17052412 0.06505159 0.94888554 0.96563203]
 [0.80839735 0.30461377 0.09767211 0.68423303]
 [0.44015249 0.12203823 0.49517691 0.03438852]]


In [390]:
#random values arrays the values will be integer with in a specific range
c = np.random.randint(10,100,(3,5)) #(min,max,(row,col))
print(c)

[[87 90 45 59 13]
 [11 15 63 13 63]
 [72 27 99 53 43]]


In [391]:
#Array of evenly spaced value --- Specifying the number of values required
d = np.linspace(10,30,6) #(min,max,no_of_element)
print(d)

[10. 14. 18. 22. 26. 30.]


In [392]:
#array of evenly spaced values -- specifying the step
e = np.arange(10,30,5) #(min,max,step)
print(e)

[10 15 20 25]


In [393]:
#convert a list into numpy array
list2 = [10,20,30,40,50]
print(list2)
print(type(list2))
np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10, 20, 30, 40, 50]
<class 'list'>
[10 20 30 40 50]


numpy.ndarray

Analysing a Numpy Array

In [394]:
c = np.random.randint(10,100,(5,5))
print(c)

[[83 71 23 57 24]
 [81 87 96 71 49]
 [94 89 91 62 33]
 [35 98 69 50 38]
 [24 54 74 98 80]]


In [395]:
#Array dimension
print(c.shape)

(5, 5)


In [396]:
#Number of dimension
print(c.ndim)

2


In [397]:
#number of element present in array
print(c.size)

25


In [398]:
#the datatype of the array element
print(c.dtype)

int64


In [399]:
#The item size in the array
print(c.itemsize)

8


In [400]:
#Total bytes in the array
print(c.nbytes)

200


Mathematical Operations On np Array

In [401]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2)  #concatenate or jion two array

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [402]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 7 0]
 [7 7 2]
 [0 7 2]]
[[12 10 14]
 [19 16 19]
 [18 16 18]]


In [403]:
print(a+b) #Its the operation of element wise addition

[[20 17 14]
 [26 23 21]
 [18 23 20]]


In [404]:
print(a-b) #Its the operation of element wise subtraction

[[ -4  -3 -14]
 [-12  -9 -17]
 [-18  -9 -16]]


In [405]:
print(a*b) #Its the operation of element wise multiplication

[[ 96  70   0]
 [133 112  38]
 [  0 112  36]]


In [406]:
print(a/b) #Its the operation of element wise division

[[0.66666667 0.7        0.        ]
 [0.36842105 0.4375     0.10526316]
 [0.         0.4375     0.11111111]]


In [407]:
print(np.add(a,b))

[[20 17 14]
 [26 23 21]
 [18 23 20]]


In [408]:
print(np.subtract(a,b))

[[ -4  -3 -14]
 [-12  -9 -17]
 [-18  -9 -16]]


In [409]:
print(np.multiply(a,b))

[[ 96  70   0]
 [133 112  38]
 [  0 112  36]]


In [410]:
print(np.divide(a,b))

[[0.66666667 0.7        0.        ]
 [0.36842105 0.4375     0.10526316]
 [0.         0.4375     0.11111111]]


Array Manipulation

In [411]:
#Random Array Generation
array = np.random.randint(0,10,(2,3)) #min,max,(row,column)
print(array)
print(array.shape)

[[7 1 0]
 [6 6 7]]
(2, 3)


In [412]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[7 6]
 [1 6]
 [0 7]]
(3, 2)


In [413]:
trans2 = array.T #Another method of transpose
print(trans2)
print(trans2.shape)

[[7 6]
 [1 6]
 [0 7]]
(3, 2)


In [414]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 2 7]
 [5 2 0]]
(2, 3)


In [415]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 2]
 [7 5]
 [2 0]]
(3, 2)


In [416]:
#Flatten to 1D
flattened = b.flatten()
print(flattened)
print(flattened.shape)

[4 2 7 5 2 0]
(6,)


Indexing And Slicing

In [417]:
arr = np.arange(1,10) #min,max  #max value is not included
print(arr)

[1 2 3 4 5 6 7 8 9]


In [418]:
print(arr[0])
print(arr[-1])

1
9


In [419]:
#Slicing
print(arr[1:4]) #start : stop  #last indexd is not included

[2 3 4]


In [420]:
print(arr[1:7:2]) #start: stop : step

[2 4 6]


In [421]:
print(arr[3:]) # 3 to last element

[4 5 6 7 8 9]


In [422]:
print(arr[:5])

[1 2 3 4 5]


In [423]:
print(arr[::2])

[1 3 5 7 9]


In [424]:
#reverse
print(arr[::-1])

[9 8 7 6 5 4 3 2 1]


Boolean Indexing

In [425]:
#Boolean Condition
condition = arr>5
print(condition)

[False False False False False  True  True  True  True]


In [426]:
#Filter value
filtered = arr[arr>5]
print(filtered)

[6 7 8 9]


In [427]:
#Multuiple condition (use & and |)
result = arr[(arr>4 )&(arr<7)]
print(result)

[5 6]


### Universal Functions

Mathematical Function

In [428]:
#Square Root
print("Square Root: ",np.sqrt(arr))

Square Root:  [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [429]:
#Exponential
print("Exponential: ",np.exp(arr))

Exponential:  [2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [430]:
#Log
print("log: ",np.log([8,16,32]))

log:  [2.07944154 2.77258872 3.4657359 ]


In [431]:
#absolute value
print("Abs: ",np.abs([-1, 34, -56]))

Abs:  [ 1 34 56]


Trigonometric Function

In [432]:
angle = np.array([30,60,90])

In [433]:
rad = np.deg2rad(angle)
print(rad)

[0.52359878 1.04719755 1.57079633]


In [434]:
print("sin: ",np.sin(rad))

sin:  [0.5       0.8660254 1.       ]


In [435]:
print("cos: ",np.cos(rad))

cos:  [8.66025404e-01 5.00000000e-01 6.12323400e-17]


Aggregate Function

In [436]:
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
print(arr1)
#basic statistics
print("sum: ",np.sum(arr))
print("min: ",np.min(arr))
print("max: ",np.max(arr))
print("mean: ",np.mean(arr))
print("median: ",np.median(arr))
print("std: ",np.std(arr))
print("var: ",np.var(arr))


[[1 2 3]
 [4 5 6]]
sum:  45
min:  1
max:  9
mean:  5.0
median:  5.0
std:  2.581988897471611
var:  6.666666666666667


In [437]:
#axis wise operation
print("sum rows: ",np.sum(arr1,axis=1))


sum rows:  [ 6 15]


In [438]:
print("sum column: ",np.sum(arr1,axis=0))

sum column:  [5 7 9]


In [439]:
#comulative sum
print("comulative sum: ",np.cumsum(arr1))

comulative sum:  [ 1  3  6 10 15 21]


In [440]:
#index of min and max
print("min index: ",np.argmin(arr1))
print("max index: ",np.argmax(arr1))

min index:  0
max index:  5


In [441]:
#Stack Array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

#vertical stack
vstack = np.vstack((arr1,arr2))
print(vstack)

[[1 2 3]
 [4 5 6]]


In [442]:
#horizontal stack
hstack = np.hstack((arr1,arr2))
print(hstack)

[1 2 3 4 5 6]


In [443]:
#split array
arr = np.arange(1,10)
print(arr)

split = np.split(arr,3) #split the arr into 3 parts
print(split)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [444]:
#Append and Insert
arr = np.array([1, 2, 3])
appended = np.append(arr,[4, 5]) #array, element or [elements]
print(appended)

inserted = np.insert(arr, 0, 100) # array, index, element or[elements]
print(inserted)


[1 2 3 4 5]
[100   1   2   3]


In [445]:
#Delete Element
deleted = np.delete(arr, 0) #array, index
print(deleted)

[2 3]


Broadcasting - Broadcasting allows opertaions on arrays of differnt sizes

In [446]:
arr = np.array([[1,2,3],[4,5,6]])
scaler = 10

#add 10 with every element of the array
print(arr+scaler)

[[11 12 13]
 [14 15 16]]


In [447]:
row = np.array([1,2,3])
#add the row array to each row of arr
print(arr+row)

[[2 4 6]
 [5 7 9]]


Coping Array

In [448]:
#view -shared data
arr = np.array([1,2,3])
view = arr.view()
view[0] = 10
print(arr)

[10  2  3]


In [449]:
#copy- independent
arr = np.array([1,2,3])
copy = arr.copy()
arr[0] = 100
print(copy)

[1 2 3]


Sorting and Searching

In [450]:
arr = np.array([3,1,2,5,9,6,4])

#sort array
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 2 3 4 5 6 9]


In [451]:
#sort indices - give the index of the sorted array
indices = np.argsort(arr)
print(indices)

[1 2 0 6 3 5 4]


In [452]:
#Find unique Value
unique = np.unique(arr)
print(unique)

[1 2 3 4 5 6 9]


In [453]:
#Finb where condition is true - return the index of the elements which satisfy the condiition
condition = np.where(arr>4)
print(condition)

(array([3, 4, 5]),)


Linear Algebra Common Operation

In [454]:

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

#dot product
dot = np.dot(a,b)
print(dot)

[[19 22]
 [43 50]]


In [455]:
#cross product
cross = np.cross(a,b)
print(cross)

[-4 -4]


/tmp/ipython-input-2644534817.py:2: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  cross = np.cross(a,b)


In [456]:
#Determinant
det = np.linalg.det(a)
print(det)

-2.0000000000000004


In [457]:
#inverse
inv = np.linalg.inv(a)
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [458]:
#Eigenvalues and Eigenvector
eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Random Number Generation

In [459]:
# With seed -set seed for reproducibility
np.random.seed(42)
print(np.random.rand(3))  # [0.37454012 0.95071431 0.73199394]

np.random.seed(42)  # Reset to same seed
print(np.random.rand(3))  # [0.37454012 0.95071431 0.73199394] - Same numbers!

# Without seed
print(np.random.rand(3))  # Different numbers each time

[0.37454012 0.95071431 0.73199394]
[0.37454012 0.95071431 0.73199394]
[0.59865848 0.15601864 0.15599452]


In [460]:
# Random float between 0-1
rand = np.random.random(5)
print(rand)

[0.05808361 0.86617615 0.60111501 0.70807258 0.02058449]


In [461]:
# Random integers
randint = np.random.randint(1, 100, size=5)
print(randint)

[ 2 88 30 38  2]


In [462]:
# Normal distribution (mean=0, std=1)
normal = np.random.randn(5)
print(normal)

[-0.46341769 -0.46572975  0.24196227 -1.91328024 -1.72491783]


In [463]:
#Choice from array
choice = np.random.choice([1,2,3,4,5,6,7,8,9],size=4)
print(choice)

[3 7 4 9]


In [464]:
#shuffle array
arr = np.array([1,2,3,4,5])
np.random.shuffle(arr)
print(arr)

[2 4 5 1 3]


Conditional Operations

In [465]:
arr = np.array([10,25,30,45,50])

#np.where - ternary operator
result = np.where(arr>30,"high","low") #condition, value_if_true, value_if_false)
print(result)

['low' 'low' 'low' 'high' 'high']


In [466]:
result = np.where(arr>30,arr,0) #condition, value_if_true, value_if_false)
print(result)

[ 0  0  0 45 50]


In [467]:
#All and Any
print(np.all(arr>4)) # Returns True only if every single element satisfies the condition.
print(np.any(arr>30)) # Returns True if at least one element satisfies the condition.

True
True


Saving and Loading Arrays

In [468]:
arr = np.array([1,2,3,4,5,6,7])


In [469]:
#save file in binary formate
np.save('my_array.npy',arr)

In [470]:
#load from file
loaded = np.load('my_array.npy')
print(loaded)

[1 2 3 4 5 6 7]


In [471]:
#save/load as text CSV like
np.savetxt('my_array.csv',arr)

In [472]:
loaded_txt = np.loadtxt('my_array.csv')
print(loaded_txt)

[1. 2. 3. 4. 5. 6. 7.]
